### ISSUE TITLE
Animations not visible on UICollectionView

### ISSUE THREAD

**Issue by R-Ashh** [marcosgriselli/ViewAnimator#62] opened 2019-12-04 14:59 UTC
Hi, thanks for the library, I have a issue with running the animation on UICollectionView, I followed the instruction step by step looking at the example in the repository, but it won't work and it doesn't show any animation, and it load data into collectionview without any animation.
![Screen Shot 2019-12-04 at 6 28 52 PM](https://user-images.githubusercontent.com/16135942/70153276-ef73d100-16c3-11ea-8fd0-ffa60b2773f4.png)

**Comment by marcosgriselli** [comment] 2019-12-04 15:10
Hi @R-Ashh. Your animation is not working because the `visibleCells` are not set yet. You need to call `reloadData()` and then animate so we can access the cells to animate. Please check the `CollectionViewController.swift` file from the Example app. It calls `reloadData()` and then performs the animations inside a `performBatchUpdates` block. This is a hack but there's no API that lets us know when a UICollectionView finishes reloading its cells.

https://github.com/marcosgriselli/ViewAnimator/blob/17e7ba9e9c9e09bfd46086e0189b198fedc67847/Example/ViewAnimator/ViewControllers/CollectionViewController.swift#L31

**Comment by R-Ashh** [comment] 2019-12-04 17:11
![Screen Shot 2019-12-04 at 8 41 12 PM](https://user-images.githubusercontent.com/16135942/70164451-6dd96e80-16d6-11ea-9e5b-ae43a32658f2.png)

I did as you said still no action.

**Comment by marcosgriselli** [comment] 2019-12-04 17:43
@R-Ashh could you create an example project with the bug and share it on GitHub? The example app is working as expected so it's hard to tell why the same code is not working for you.

**Comment by R-Ashh** [comment] 2019-12-04 18:18
thank you for your fast response, I found the issue, when I do the filling like the example project with a button, and first remove it and add it again it workes, but when I call a method in ViewDidLoad for generating data and reloading the data inside UI collection view like the image above it doesn't work properly and data is already there when I open the ViewController I even tried to generate the data with 1.5 delays with asyncAfter still it loads without any animation and solid. I can give you access to my project in gitlab if you want to see it. thanks in advance.

**Comment by marcosgriselli** [comment] 2019-12-04 18:43
@R-Ashh I just tried what you mention on the example project and it works. A reproduction small project on GitHub would be a lot more useful so other people can look at it. You could also fork this project and reproduce the issue in the example app if you don't want to create a new repository with your code.

**Comment by marcosgriselli** [comment] 2019-12-06 20:54
@R-Ashh any update on this?

**Comment by R-Ashh** [comment] 2019-12-07 11:31
Hi, I fixed the problem with another solution, like the image below and it worked, still have an issue but it works like this right now, I will create a sample project later to show you the exact problem and let you know about it. 
![Screen Shot 2019-12-07 at 3 00 46 PM](https://user-images.githubusercontent.com/16135942/70373915-5bdc1380-1902-11ea-855c-0ed656a5612c.png)

**Comment by marcosgriselli** [comment] 2019-12-07 11:55
Perfect, I'm closing this issue for the moment until we have a clearer picture of the problem.

**Closed by marcosgriselli** 2019-12-07 11:55 UTC
